### ISSUE TITLE
[Help] error on with some commands

### ISSUE THREAD

**Issue by bluebyt** [killown/waypy#1]
This command is working: sock.set_workspace({"x":2, "y":2})

But this command give me an error: sock.go_next_workspace()

Traceback (most recent call last):
  File "/home/bluebyt/.config/ipc-scripts/./workspace2.py", line 8, in <module>
    sock.go_next_workspace()
  File "/home/bluebyt/.local/lib/python3.11/site-packages/wayfire.py", line 411, in go_next_workspace
    self.set_workspace(next)
  File "/home/bluebyt/.local/lib/python3.11/site-packages/wayfire.py", line 945, in set_workspace
    x, y = workspace["x"], workspace["y"]
           ~~~~~~~~~^^^^^
TypeError: 'int' object is not subscriptable

Archlinux
python 3.11.8
dbus-python 1.3.2

I want try this scripts, after you answered to me here:
[ipc: support workspace sets](https://github.com/WayfireWM/wayfire/pull/2156)

**Comment by killown** [comment]
I fixed sock.go_next_workspace() but this function will just go to the next workspace, if you want go only for workspaces with views then you need sock.go_next_workspace_with_views()

update the module:
```
git clone https://github.com/killown/waypy
cd waypy
python3 -m pip install .
```

**Comment by bluebyt** [comment]
I updated but I get another error.
Traceback (most recent call last):
  File "/home/bluebyt/.config/ipc-scripts/./workspace2.py", line 4, in <module>
    sock.set_workspace({"x":1, "y":1}, focused_view_id)
  File "/home/bluebyt/.local/lib/python3.11/site-packages/wayfire.py", line 1126, in set_workspace
    focused_output = self.get_focused_output()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bluebyt/.local/lib/python3.11/site-packages/wayfire.py", line 407, in get_focused_output
    return self.send_json(message)["info"]
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bluebyt/.local/lib/python3.11/site-packages/wayfire.py", line 80, in send_json
    return self.read_message()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/bluebyt/.local/lib/python3.11/site-packages/wayfire.py", line 69, in read_message
    raise Exception(response["error"])
Exception: No such method found!

**Comment by killown** [comment]
"vswitch/set-workspace"

you need the plugin vswitch enabled

**Comment by killown** [comment]
can you update the module again, I added list_methods

you can check every method and respective plugin using print(sock.list_methods())

**Comment by bluebyt** [comment]
Yes I have the plugin vswitch enabled.
Wayfire.ini
plugins = ipc ipc-rules stipc alpha animate autostart command cube expo fast-switcher fisheye grid foreign-toplevel gtk-shell idle move place resize switcher vswitch window-rules wm-actions wobbly wrot zoom scale wf-info background-view wsets

I am not sure how to use the command print(sock.list_methods())

I added this in my script:

![20240322_143631](https://github.com/killown/waypy/assets/18442224/82f792dc-e93c-49c1-886e-f67e87e98aa7)

Error: 
Traceback (most recent call last):
  File "/home/bluebyt/.config/ipc-scripts/./workspace2.py", line 11, in <module>
    sock.go_next_workspace()
  File "/home/bluebyt/.local/lib/python3.11/site-packages/wayfire.py", line 589, in go_next_workspace
    workspaces = list(self.total_workspaces().values())
                      ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bluebyt/.local/lib/python3.11/site-packages/wayfire.py", line 881, in total_workspaces
    winfo = self.get_active_workspace_info()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bluebyt/.local/lib/python3.11/site-packages/wayfire.py", line 499, in get_active_workspace_info
    focused_output = self.get_focused_output()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bluebyt/.local/lib/python3.11/site-packages/wayfire.py", line 472, in get_focused_output
    return self.send_json(message)["info"]
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bluebyt/.local/lib/python3.11/site-packages/wayfire.py", line 100, in send_json
    return self.read_message()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/bluebyt/.local/lib/python3.11/site-packages/wayfire.py", line 81, in read_message
    raise Exception(response["error"])
Exception: No such method found!

**Comment by killown** [comment]
> Yes I have the plugin vswitch enabled. Wayfire.ini plugins = ipc ipc-rules stipc alpha animate autostart command cube expo fast-switcher fisheye grid foreign-toplevel gtk-shell idle move place resize switcher vswitch window-rules wm-actions wobbly wrot zoom scale wf-info background-view wsets
> 
> I am not sure how to use the command print(sock.list_methods())
> 
> I added this in my script:
> 
> ![20240322_143631](https://private-user-images.githubusercontent.com/18442224/316133624-82f792dc-e93c-49c1-886e-f67e87e98aa7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExNDI2MDgsIm5iZiI6MTcxMTE0MjMwOCwicGF0aCI6Ii8xODQ0MjIyNC8zMTYxMzM2MjQtODJmNzkyZGMtZTkzYy00OWMxLTg4NmUtZjY3ZTg3ZTk4YWE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIyVDIxMTgyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNiYzVmYjNmMmRkYmEwMTIzYTU4Yjc3ZjQzMWQxMDFkOTJhNjQ0OTlmMmJlYWFjMGUwYzM5MmM1MTgyOGMzOWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fA1e4w9BWJeEn-uFiXcoYz1WsZsrwO58DPQol233LIA)
> 
> Error: Traceback (most recent call last): File "/home/bluebyt/.config/ipc-scripts/./workspace2.py", line 11, in sock.go_next_workspace() File "/home/bluebyt/.local/lib/python3.11/site-packages/wayfire.py", line 589, in go_next_workspace workspaces = list(self.total_workspaces().values()) ^^^^^^^^^^^^^^^^^^^^^^^ File "/home/bluebyt/.local/lib/python3.11/site-packages/wayfire.py", line 881, in total_workspaces winfo = self.get_active_workspace_info() ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/bluebyt/.local/lib/python3.11/site-packages/wayfire.py", line 499, in get_active_workspace_info focused_output = self.get_focused_output() ^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/bluebyt/.local/lib/python3.11/site-packages/wayfire.py", line 472, in get_focused_output return self.send_json(message)["info"] ^^^^^^^^^^^^^^^^^^^^^^^ File "/home/bluebyt/.local/lib/python3.11/site-packages/wayfire.py", line 100, in send_json return self.read_message() ^^^^^^^^^^^^^^^^^^^ File "/home/bluebyt/.local/lib/python3.11/site-packages/wayfire.py", line 81, in read_message raise Exception(response["error"]) Exception: No such method found!

list_methods will return a list of methods, just to check the available methods you can use, you can ignore it, not useful in your script!

about the focused_output, you need to install the latest wayfire-git

**Comment by bluebyt** [comment]
I retried  the script since it has been updated, now the next workspace `sock.go_next_workspace()` command works, but not the previous workspace

`sock.go_previous_workspace()`

`Traceback (most recent call last):
  File "/home/bluebyt/.config/ipc-scripts/workspace2.py", line 11, in <module>
    sock.go_previous_workspace()
  File "/home/bluebyt/.local/lib/python3.12/site-packages/wayfire/core/ipc_utils.py", line 378, in go_previous_workspace
    self.set_workspace(previous)
  File "/home/bluebyt/.local/lib/python3.12/site-packages/wayfire/ipc.py", line 363, in set_workspace
    x, y = workspace["x"], workspace["y"]
           ~~~~~~~~~^^^^^
TypeError: 'int' object is not subscriptable`
